#ifndef __CSI_CONFIG_H__
#define __CSI_CONFIG_H__

//#define CONFIG_KERNEL_FREERTOS 1  //用到freertos就打开此宏
#define CONFIG_ARCH_RV32 1
#define CONFIG_CPU_E906 1
#define CONFIG_RV32_CORETIM 1
#define CONFIG_CHIP_SMARTL_RV32 1
#define CONFIG_BOARD_SMARTL_E906_EVB 1
#define CONFIG_BOARD_NAME_STR "APT32F173"
#define CONFIG_SUPPORT_TSPEND 1
#define CONFIG_NEWLIB_WRAP 1
#define CONFIG_USER_DEFINED_LD_DIR_STR ""


#endif
